// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTUaQa134GsNWOD7DGvhxD7KiIjL-TfE',
    appId: '1:177654884116:web:786b94050444820f964401',
    messagingSenderId: '177654884116',
    projectId: 'miniumworld-9bded',
    authDomain: 'miniumworld-9bded.firebaseapp.com',
    storageBucket: 'miniumworld-9bded.firebasestorage.app',
    measurementId: 'G-Z3SJ7C6FG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqI-LWxXS1mpVmWrgJWfYr7frgr8CwrHY',
    appId: '1:177654884116:android:f56803e50f89f439964401',
    messagingSenderId: '177654884116',
    projectId: 'miniumworld-9bded',
    storageBucket: 'miniumworld-9bded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvtJ0ol8Vw5huVKcwYFRqIzJW1mbxiZfE',
    appId: '1:177654884116:ios:248311af512e2e96964401',
    messagingSenderId: '177654884116',
    projectId: 'miniumworld-9bded',
    storageBucket: 'miniumworld-9bded.firebasestorage.app',
    iosBundleId: 'com.example.minionworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvtJ0ol8Vw5huVKcwYFRqIzJW1mbxiZfE',
    appId: '1:177654884116:ios:248311af512e2e96964401',
    messagingSenderId: '177654884116',
    projectId: 'miniumworld-9bded',
    storageBucket: 'miniumworld-9bded.firebasestorage.app',
    iosBundleId: 'com.example.minionworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUTUaQa134GsNWOD7DGvhxD7KiIjL-TfE',
    appId: '1:177654884116:web:ddb0dfed8a0d875b964401',
    messagingSenderId: '177654884116',
    projectId: 'miniumworld-9bded',
    authDomain: 'miniumworld-9bded.firebaseapp.com',
    storageBucket: 'miniumworld-9bded.firebasestorage.app',
    measurementId: 'G-LG65WWF7FZ',
  );
}
